tipi-tapi/ai-paint-today-BE

- .github/workflows/cd.yml
- src/main/resources/application-prod.yml
- actions secret 값들은 비공개 내부 자료 페이지에 올렸습니다 :)
- aws ec2 private key 또한 비공개 내부 자료 페이지에 있습니다. 다운로드 받아서 ssh 연결하면 ec2 접속 가능합니다!
- application-prod.yml 파일 생성했습니다.
- [노션 참고 링크](https://knowing-jester-927.notion.site/cd-099844f934044918b6ca6a1d8877eb9e)
- main에 push될 때 배포하도록 설정했는데 배포중 문제가 발생할 경우를 대비해서 main 브랜치 병합 전 release 브랜치를 만들어 release 브랜치에 push할 경우 배포되도록 설정하는 방법은 어떤가요?
close #15
> 인프라 구축 및 cd(github actions) 구현

- .github/workflows/cd.yml
- github actions cd 설정파일에 aws, openai 시크릿키 설정
> Release 0.0.1(dev)

- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- swagger 도메인 운영서버 url http -> https로 변경
close #40
> Swagger curl 요청 실패 문제 해결

- src/main/java/tipitapi/drawmytoday/emotion/service/EmotionService.java
EmotionService의 createEmotions 메소드에 `@Transactional` 을 적용함
close #48
> createEmotions 메소드 Transactional 적용

- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
- 유저가 하루에 생성할 수 있는 일기를 한 개로 제한하는 로직 구현
close #54
> 한 유저당 하루에 1개 이상 일기 생성을 제한하는 로직 생성

- src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
- validateUserWithDrawLimit 메소드 NullPointerException 발생 문제 해결
close #73
> validateUserWithDrawLimit 메소드의 NullPointerException 발생 문제 해결

- .github/workflows/cd.yml
- src/main/java/tipitapi/drawmytoday/common/utils/Encryptor.java
- 암호화, 복호화 메서드가 받은 text의 null 체크 추가
- cd.yml 오타 수정
close #84
> 일기 암호화, 복호화시 text 값이 null이면 암호화, 복호화 실패 문제 해결

- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- swagger test 도메인이 먼저 선택되도록 변경
close #87
> 스웨거 테스트 도메인이 먼저 선택되도록 변경 

- src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
- request로 받은 keyword nullable true로 변경
- 프롬프트 생성 로직 변경
close #89
> 일기 생성시 키워드 없이도 생성되도록 변경

- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
DiaryServcieTest 일부 mock 추가
- PromptService
- Encryptor
close #103
> DiaryServcieTest 일부 mock 추가

- src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryExistByDateResponse.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
[GET] /diary/calendar/date 특정 날짜 일기 존재 여부 조회 API 추가
- Controller, Service, Repository 메소드 추가
- 테스트 코드 추가
- DateUtils의 Date 반환 및 검증 메소드 추가
close #125
> :sparkles: feature: 특정 날짜 일기 존재 여부 조회 API 추가

- .github/workflows/cd.yml
PRESIGNED_IMAGE_EXPIRATION_ADMIN_DIARIES 환경변수를 cd 파일에 반영
close #116
> 환경변수 cd 파일에 반영

- .github/workflows/cd.yml
- cd 배포파일 ios private id 에서 ios private key로 수정
close # (issue)
> cd ios private key로 수정

- docker-compose.yml
docker-compose.yml에서 컨테이너명의 네이밍 컨벤션이 잘못 적용되어 있고, DB명이 잘못 설정되어있어 수정하였습니다.
수정을 거치면서 reformat되었습니다.
close # (issue)
> docker-compose의 컨테이너, db명 수정

- src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
- src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
- 기존에 키워드가 100자를 초과하지 않도록 substring 하는 로직 삭제, 테스트 삭제
- 생성한 전체 프롬프트가 1000자를 초과할 경우 substring 하는 로직 추가, 테스트 추가
close #152
> 전체 프롬프트가 1000자를 초과하지 않게 substring 처리

- src/main/java/tipitapi/drawmytoday/diary/service/ValidateDiaryService.java
- 일기 생성 시 오늘 날짜의 일기가 없을 때만 일기 작성할 수 있도록 수정
close # (issue)
> 일기 생성 시 오늘 날짜의 일기가 없을 때만 일기 작성할 수 있도록 수정

- src/main/java/tipitapi/drawmytoday/domain/ticket/service/TicketService.java
- src/test/java/tipitapi/drawmytoday/domain/ticket/service/TicketServiceTest.java
정책 변경에 따라 회원가입시 티켓 1장만 발급되도록 변경하겠습니다.
Release 1.1.4 노트에도 추가하겠습니다!
expected)
> 회원가입시 티켓 1장만 발급되도록 변경

- src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
ImageDto -> GetImageResponse로 변경되는 과정에서 수정되지 않은 테스트 수정
- DiaryControllerTest가 ImageDto로 작업되어 있어 수정함
DiaryController 문법 오류 수정
- } 가 누락되어 수정함
expected)
> 이미지 재생성 작업시 발생한 버그 수정

- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
- 테스트 서버 도메인 이름 변경에 따른 Swagger 설정 변경
- 테스트 일기 생성 시 티켓을 소모하도록 변경(프론트 요청사항)
expected)
> Swagger 테스트 서버 도메인 이름 변경 및 테스트 일기 생성 시 티켓 소모하도록 변경

- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/Diary.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/Image.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/ReviewType.java
- src/main/java/tipitapi/drawmytoday/domain/diary/dto/ReviewDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/domain/diary/exception/NotOwnerOfDiaryException.java
- src/main/java/tipitapi/drawmytoday/domain/diary/exception/NotOwnerOfImageException.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ValidateImageService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/ImageControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/PromptTextServiceTest.java
- src/test/resources/tipitapi/drawmytoday/domain/diary/repository/GetDiariesForMonitorAsPageTest.sql
- Diary review 컬럼 삭제
- Image review 컬럼 생성(1~5 사이의 String값)
- ReviewType 이넘 클래스는 삭제했습니다.
- 실패하는 테스트 수정
**테스트 서버와 실 서버에 적용해야 할 SQL 스키마**
```sql
ALTER TABLE image ADD review varchar(255);
ALTER TABLE diary DROP review;
```
close #230 
expected)
> 유저 그림 평가시 (GOOD, BAD) 평가 방식에서 1~5 사이의 숫자값을 받도록 수정

- src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
- src/main/java/tipitapi/drawmytoday/domain/r2/service/R2Service.java
R2Service, ImageService, CreateKarloImageRequest 클래스들이 이미지 확장자 정보를 필요로 합니다. 따라서 처음에는 환경변수로 뺄 생각이었으나 이미지 확장자 정보가 계속 변하지 않을거 같고, CreateKarloImageRequest 클래스 같이 `@Value` 애노테이션을 사용하기 애매한 클래스에 적용하기 힘들다는 단점이 있습니다. 
결국 환경변수로 이미지 확장자 정보를 관리하는 것이 아닌, 전역 상수로 관리하려 했으나, 지금까지 저희 프로젝트에서 상수들을 모아 따로 관리하지 않았기에.. 바로 적용하기는 애매해서 일단 각 클래스마다 하드코딩으로 확장자명을 변경해주었습니다.
민지님 생각에는 상수로 관리하는 것이 좋아 보이는지, 아니면 각 클래스마다 하드코딩하는게 좋아 보이는지 의견 부탁드립니다!
- karlo 이미지 파일 확장자 변경(png -> webp)
close #261 
expected)
> karlo 이미지 파일 확장자 변경

- src/main/java/tipitapi/drawmytoday/domain/diary/dto/CreateTestDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/TestDiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloServiceTest.java
해당 파라미터 추가 요청이 들어와 작업을 진행했습니다.
- numInferenceSteps, guidanceScale, scheduler 파라미터 추가
- 파라미터 추가로 인해 실패하는 테스트 수정
expected)
> 테스트 일기 API 호출시 karlo에 요청할 파라미터 추가

- src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
- prompt : 감정, 색상, Impressionist oil painting, 일기
- negative : photo, picture, camera, realistic, filim, movie, real, high quality, Scary, cruel, gross, sensational, solid color, not cute
- 세밀함(num_inference_steps) = 100
- 세부 완성도(guidance_scale) = 20
close #273 
expected)
> 프롬프트 개선 작업 서버에 반영

- .github/workflows/cd.yml
- src/main/java/tipitapi/drawmytoday/domain/r2/service/R2PreSignedService.java
- src/main/resources/application-r2.yml
- R2 custom domain이 곧 만료되어 교체
- R2 custom domain 환경변수 actions secret 등록
close #285 
expected)
> R2 커스텀 도메인 변경

- src/main/java/tipitapi/drawmytoday/common/validator/DiaryDateValidator.java
- src/main/java/tipitapi/drawmytoday/common/validator/ValidDiaryDate.java
문제 상황은 #292 이슈를 확인해주세요!
- 내일의 일기까지는 작성 가능하도록 변경
close #292
expected)
> 한국보다 시차가 빠른 나라에서 오늘 일기 작성시 이슈 해결

- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/domain/Message.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/dto/GptChatCompletionsRequest.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/service/GptService.java
- gpt api 파라미터 추가
- temperature: 0
- max_tokens: 100
- gpt api 응답값 clamping
close #310 
expected)
> 프롬프트 생성을 위해 호출하는 gpt api에 파라미터 추가 및 문자열 처리 작업

- src/main/java/tipitapi/drawmytoday/domain/diary/dto/ReviewDiaryRequest.java
- review 값이 숫자가 아니거나 없으면 예외 반환
- 숫자 값이 1보다 작으면 1로 변환
- 숫자 값이 5보다 크면 5로 변환
close #315
expected)
> :hammer: refactor: 이미지 평가 review값 clamping하도록 변경

- src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
> Release 1.3.2

- .github/workflows/cd.yml
- src/main/java/tipitapi/drawmytoday/common/config/RestTemplateConfig.java
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/stability/dto/CreateStabilityImageRequest.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/stability/exception/StabilityRequestFailException.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/stability/service/StabilityImageService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/stability/service/StabilityRequestService.java
- src/main/java/tipitapi/drawmytoday/domain/user/dto/AutoLoginRequest.java
- src/main/resources/application-kakao.yml
- src/main/resources/application.yml
- karlo -> stable diffusion으로 변경
close #323
expected)
> diary image generator 변경
