tipi-tapi/ai-paint-today-BE

- src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
- src/main/java/tipitapi/drawmytoday/diary/domain/Image.java
- src/main/java/tipitapi/drawmytoday/diary/dto/GetDiariesResponse.java
- src/main/java/tipitapi/drawmytoday/diary/dto/GetMonthlyDiariesResponse.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
- src/test/java/tipitapi/drawmytoday/common/testdata/TestEmotion.java
- src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
- 월별 일기 목록 api 구현 시
- 연도를 쿼리 파라미터로 받도록 추가했습니다.
- Diary를 가져올 때 Image들도 손쉽게 가져오기 위해 Diary와 Image를 양방향 매핑하였습니다.
- 연도와 월 값을 LocalDateTime으로 변환하는 DateUtils 클래스를 만들었습니다.
- 테스트도 구현했습니다.(나중에 Controller 단위 테스트도 추가하겠습니다)
close #23
> 월별 일기 목록 api 구현

- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/dto/GetLastCreationResponse.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
- src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
- [GET] /diary/last-creation : 마지막 일기 생성 시각 조회 API 추가
- Repository Test 추가
- Service Test 추가
- Diary ID, 생성 시각, 감정, User ID를 파라미터로 Test Diary를 생성하는 메소드 추가
close #27
> 마지막 일기 생성 시각 조회 API

- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
- src/main/java/tipitapi/drawmytoday/diary/dto/UpdateDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
[PUT] /diary/:id : 일기 수정 API
- 일기 내용(notes) 수정
- null 값으로 요청할 경우, 내용이 삭제됨
- Service Test 추가
close #29
> :sparkles: feature: 일기 수정 API 추가

- src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/s3/service/S3Util.java
S3 URI가 아니라, Full S3 URL을 반환하도록 수정
일기 조회 API : [GET] /diary/:id
-  기존에는 "post/3/123142_1.png"와 같이 S3 URI로 리턴하였는데, "https://버킷이름.s3.지역이름.amozon.com/이미지URI" 형식인 Full S3 URL로 리턴하도록 변경함
- S3 Service에 S3 Full URL을 만드는 메소드를 추가할 경우, DiaryService가 S3Client가 주입된 S3Service를 불필요하게 주입받게 되므로, 별도의 빈인 S3Util에 메소드를 추가해, S3Client 없는 비교적 가벼운 빈을 주입받도록 함
close #36
> 일기 조회 API가 이미지에 대해 Full S3 Url을 반환하도록 수정

- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- swagger 도메인 운영서버 url http -> https로 변경
close #40
> Swagger curl 요청 실패 문제 해결[배포]

- .github/workflows/cd.yml
- src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
- src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
- src/main/java/tipitapi/drawmytoday/oauth/domain/Auth.java
- src/main/java/tipitapi/drawmytoday/oauth/dto/AppleIdToken.java
- src/main/java/tipitapi/drawmytoday/oauth/dto/RequestAppleLogin.java
- src/main/java/tipitapi/drawmytoday/oauth/exception/OAuthNotFoundException.java
- src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
- src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
- src/main/java/tipitapi/drawmytoday/oauth/service/OAuthService.java
- src/main/java/tipitapi/drawmytoday/user/domain/User.java
- src/main/java/tipitapi/drawmytoday/user/exception/DuplicateUserException.java
- src/main/java/tipitapi/drawmytoday/user/repository/UserRepository.java
- src/main/java/tipitapi/drawmytoday/user/service/UserService.java
- src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
__구글, 애플 소셜로그인(회원가입), 회원탈퇴 기능 리팩토링 및 테스트 완료__
- 소셜로그인 성공시 유저의 이메일 대조 뿐만 아니라 delete 유무까지 확인하여 회원가입한 유저인지 체크하도록 변경
- 구글, 애플 소셜로그인 탈퇴 기능 구현
- 탈퇴 요청 성공시 소셜로그인 탈퇴
- 탈퇴 요청 성공시 유저를 db에서 삭제하는 것이 아닌 deletedAt으로 탈퇴 시각을 저장하도록 구현(재 회원가입시 새로운 유저 생성)
- 프론트에서 탈퇴 요청을 보낼 때 토큰 만료시 access token 재발급 요청을 먼저 보내 토큰을 재발급받고, 탈퇴 요청을 보내는 시나리오 테스트 완료
- swagger에 oauth 요청시 발생할 수 있는 모든 에러 명시 완료
- 에러 메시지 인코딩 실패 오류 해결
- user 엔티티에 oauth_type 필드 삭제(social_code와 중복)
```
로컬 서버에도 적용해주세요!
alter table user drop oauth_type;
```
close #21 #44
> 소셜로그인 오류 해결 및 리팩토링

- src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtProperties.java
- src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtTokenProvider.java
- src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtType.java
- src/main/java/tipitapi/drawmytoday/common/utils/HeaderUtils.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/emotion/controller/EmotionController.java
- src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
- 테스트용 JWT 토큰 만료 API 구현
- request header 안에 토큰 가져오는 로직 통일화
- swagger security scheme 등록 방식 bean -> annotation으로 변경 (일부 예외상황 설정을 편하게 하기 위해)
- jwt 토큰이 필요없는 api의 경우 authorization 헤더에 토큰이 등록되지 않도록 변경
close #53
> JWT 토큰 만료 API(테스트용) 및 Swagger security 등록 방식 변경

- src/main/java/tipitapi/drawmytoday/emotion/controller/EmotionController.java
- src/main/java/tipitapi/drawmytoday/emotion/dto/GetActiveEmotionsResponse.java
- src/main/java/tipitapi/drawmytoday/emotion/service/EmotionService.java
- src/test/java/tipitapi/drawmytoday/diary/service/EmotionServiceTest.java
[GET] emotions/all 감정 목록 조회 API
- `lan` query parameter를 추가해, 언어 설정을 요청받도록 했습니다.
- `ko`, `en` 값을 요청받을 수 있으며, 이 외의 값을 요청하거나 값을 전달하지 않았을 경우 `ko`로 처리됩니다.
- `en`을 요청 받을 경우, 영어로 반환하는 경우이므로 Emotion의 emotionPrompt 객체 값으로 반환됩니다.
close #64
> :sparkles: feature: 감정 목록 조회 API 언어 파라미터 추가

- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
GlobalExceptionHandler에서 RestClientException을 처리하는 handleRestClientException 메소드는 
기존에 OAUTH_SERVER_FAILED로 핸들링하였으나, 
DALL-E 요청에서도 RestClientException이 발생할수 있기 때문에, 공통적인 예외인 REST_CLIENT_FAILED로 핸들링하도록 수정함
아래 Conversation에서 이야기 나누었으나 누락되어 수정함
https://github.com/tipi-tapi/ai-paint-today-BE/pull/51#discussion_r1235007444
close #67 
참고 #51
> RestClientException 발생시 GlobalExceptionHandler가 공통적인 예외로 핸들링하도록 수정

- src/main/java/tipitapi/drawmytoday/diary/dto/GetMonthlyDiariesResponse.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- [GET] /diary/calendar/monthly 월별 일기 조회 API
- 기존에는 이미지 URI만 반환함
- Presigned URL 처리가 된 Full Image Url로 반환하도록 수정함
close #77
> 월별 일기 조회 API가 반환하는 이미지 URL을 FULL 이미지 URL로 반환하도록 수정

- src/main/java/tipitapi/drawmytoday/DrawMyTodayApplication.java
- src/main/java/tipitapi/drawmytoday/common/config/DevConfig.java
- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- src/main/java/tipitapi/drawmytoday/dev/controller/DevelopController.java
- src/main/java/tipitapi/drawmytoday/health/controller/HealthCheckController.java
- src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
- src/main/java/tipitapi/drawmytoday/test/controller/TestController.java
- health 도메인에 서버 생존 검증 api 추가
- 토큰 만료 api를 기존 auth 도메인에서 dev 도메인으로 이동
- dev 도메인은 prod 프로필일 경우 컴포넌트 스캔 대상에서 제외하도록 설정
close #69
> 서버 생존 검증 api 추가 및 테스트용 토큰 만료 api 테스트 도메인으로 이동

- build.gradle
- src/test/resources/application.yml
ci 서버에서 테스트한 환경이랑 동일하게 맞추기 위해 테스트 환경을 인텔리제이가 아닌 Gradle로 돌리도록 바꾸었습니다. 다만 Gradle로 테스트를 돌릴 시 테스트 속도가 느리다는 단점이 있습니다 ^^;
설정 방법은 다음과 같습니다.
1. Preferences -> Build, Execution, Deployment -> Build Tools -> Gradle에서 Build and Run을 둘 다 Gradle로 변경합니다.
2. Run/Debug Configurations -> Edit configuration templates -> Gradle에서 Environment variables를 설정합니다.
3. 테스트를 실행하면 Gradle 템플릿에 적용한 환경변수가 등록되어 테스트가 동작합니다.
close #82
> 테스트 환경 Gradle로 변경

- src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
- src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
- Error Response시 Error code가 아닌 Error name이 반환되는 문제 해결
- 일기 생성시 하루에 여러번 생성 가능하도록 변경(광고 도입 후 다시 막을 예정)
close #91
> 에러 코드에 이름이 넘어가는 문제 해결 및 일기 생성 제한 해제

- src/main/java/tipitapi/drawmytoday/user/domain/User.java
- src/main/java/tipitapi/drawmytoday/user/repository/UserRepository.java
- src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
- src/test/java/tipitapi/drawmytoday/diary/repository/UserRepositoryTest.java
- User 엔티티에 @Where 애노테이션 적용
- 앞에 두 애노테이션 추가에 따른 UserRepository, UserService 로직 수정
- UserRepository 메서드들 테스트 검증 로직 추가
__@SQLDelete도 추가하고 싶었지만 user 테이블이 SQL 키워드이기에 identifier 에러가 떠서.. 그냥 deleteAt을 update하여 삭제하는 방식 그대로 가겠습니다.__
close #62
>  User 엔티티에 Soft delete 애노테이션 추가

- src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
- src/main/java/tipitapi/drawmytoday/health/controller/HealthCheckController.java
- src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
- health check api를 토큰 없이 호출 가능하도록 수정
- health check api의 http method를 GET -> HEAD 변경(GET보다 더 가볍고 빠름)
- swagger에 명세된 회원 탈퇴 api의 성공 응답 코드가 204만 존재하도록 변경
- AuthController의 구글 로그인, 애플 로그인, jwt access token 재발급 api의 response 타입을 ResponseEntity<SuccessResponse<~~>>로 변경(response type을 통일했어야 했는데 그대로 반환하고 있었기에 변경했습니다. 프론트에게도 해당 이슈를 전달해 바뀐 response에 맞게 수정하도록 하겠습니다)
close #95
> health check api 및 swagger 에러 수정

- src/main/java/tipitapi/drawmytoday/common/response/SuccessResponse.java
- src/test/java/tipitapi/drawmytoday/response/SuccessResponseTest.java
- SuccessResponse에서 data를 파싱할 때 값이 빈 비열이면 빈 배열이 반환되도록 변경
- SuccessResponse 테스트코드 작성(원래는 컨트롤러 메서드에 직접 넣어 테스트환경을 구축하려 했으나 시간이 많이 걸릴것 같아 objectMapper를 사용하여 파싱하는 방향으로 바꿨습니다)
close #97
> http response시 빈 배열일 경우 빈 배열을 반환하도록 변경

- src/test/resources/tipitapi/drawmytoday/adreward/repository/ExpiredAdReward.sql
- src/test/resources/tipitapi/drawmytoday/adreward/repository/ValidAdReward.sql
기존에 광고 리워드 도메인을 작업하면서, 광고의 유형을 나타낸 AdType 엔티티가 작업 도중 사라졌으나, 테스트용 SQL 파일에서 삭제되지 않았기에, 이를 삭제하였습니다.
close #100
> 테스트용 SQL 파일에서 AdType 삭제

- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
[POST] /diary 일기 생성 API
- 일기 생성시 `test`라는 query parameter가 true 값으로 주어질 경우, dummy 일기로 생성함
- dall-e에 요청하여 이미지를 생성하지 않고, s3에 새로운 이미지를 게시하지 않음
- s3에 미리 등록해둔 테스트용 이미지의 URI로 Image 객체가 생성됨 ( s3://bucket-8th-team4/test/dummy.png )
close #106
> 일기 생성시, 테스트 용으로 생성할 수 있는 기능 추가

- src/main/java/tipitapi/drawmytoday/adreward/service/UseAdRewardService.java
- src/main/java/tipitapi/drawmytoday/adreward/service/ValidateAdRewardService.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryLimitResponse.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/user/domain/User.java
- src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
- src/test/java/tipitapi/drawmytoday/adreward/service/ValidateAdRewardServiceTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
- 광고 리워드의 유효 시간을 1시간으로 변경
- [GET] /diary/limit 일기 생성 가능 여부 조회 API
- 금일 유저가 이미 일기를 생성했다면, available = false, 마지막 일기 생성 일자를 반환한다.
- 하지만, 유저가 유효한 리워드가 있다면 available = true, 리워드 생성 일자를 반환한다.
- 리워드와 관계 없이, 유저가 금일 생성한 일기가 없다면, available = true를 반환한다.
- 유저가 일기를 생성한 적이 없는 경우가 포함된다.
close #108
> 광고 리워드 유효 시간 변경, 일기 생성 가능 여부 조회 API 추가

- src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
- src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
- 일기 생성 시 빈 키워드를 받으면 키워드 자리에 emotional을 작성하도록 수정
close #117
>  일기 생성시 빈 키워드를 받으면 키워드 자리에 Emotional을 작성하도록 수정

- src/main/java/tipitapi/drawmytoday/admin/controller/AdminController.java
- src/main/java/tipitapi/drawmytoday/admin/dto/GetDiaryAdminResponse.java
- src/main/java/tipitapi/drawmytoday/admin/service/AdminService.java
- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/diary/dto/DiaryForMonitorQueryResponse.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
- src/main/java/tipitapi/drawmytoday/diary/service/AdminDiaryService.java
- src/main/java/tipitapi/drawmytoday/user/domain/User.java
- src/main/java/tipitapi/drawmytoday/user/domain/UserRole.java
- src/main/java/tipitapi/drawmytoday/user/exception/UserAccessDeniedException.java
- src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
- src/test/java/tipitapi/drawmytoday/admin/controller/AdminControllerTest.java
- src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
- src/test/java/tipitapi/drawmytoday/common/testdata/TestUser.java
- src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
- src/test/resources/tipitapi/drawmytoday/diary/repository/GetAllDiariesForMonitorAsPageTest.sql
관리자 권한 Enum 추가
- UserRole.ADMIN 추가
- UserRole.GUEST 삭제
User의 관리자 검증 메소드 추가
- ValidateUserService.validateAdminUserById() 메소드 추가
- 해당 유저가 관리자 권한인지 반환하는 User.isAdmin() 메소드 추가
관리자용 일기 목록 조회 API 추가
- [GET] /admin/diaries
- admin 패키지의 AdminController, AdminService 클래스 추가
- diary 패키지의 AdminDiaryService 추가
- diary 패키지의 DiaryRepository에 getAllDiariesForMonitorAsPage 메소드 추가
- 일기 자체를 반환하는 작업은 diary 패키지에서 처리하는것이 도메인 분류상 맞기 때문에, AdminController가 AdminService를 호출하면, AdminService가 AdminDiaryService를 통해 일기 데이터를 받아옵니다.
- AdminService는 받아온 일기 데이터를 응답 dto에 맞게 처리하여 AdminController로 반환합니다.
관리자 테스트 유저 객체 생성 메소드 추가
- TestUser 클래스에 createAdminUserWithId 메소드 추가
close #116
> 관리자용 일기 이미지/프롬프트 목록 조회 API 추가

- src/main/java/tipitapi/drawmytoday/admin/service/AdminService.java
- src/main/resources/application.yml
관리자용 일기 목록 조회시 이미지 S3 URL로 발급
- 기존에는 이미지 URI로 발급했으나, S3 Presigned URL로 발급하도록 수정
- 환경변수 PRESIGNED_IMAGE_EXPIRATION_ADMIN_DIARIES 을 등록하여, 이미지 유효시간을 유연하게 변경할 수 있도록 함
- 환경변수 노션/Github Actions Secret 등록 완료!
close #116
> 관리자용 일기 목록 조회시 이미지 S3 URL로 발급

- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
- DiaryRepository의 getAllDiariesForMonitorAsPage 메서드 네이티브쿼리 오타 수정(Diary -> diary)
위와 같이 Diary라고 작성하면 테이블을 못 찾아서 수정했습니다!
- 자잘한 네이밍 수정
- 일기 생성 가능 여부 조회 API의 스웨거 설명 수정
> 자잘한 버그와 네이밍 수정

- .github/workflows/cd.yml
- build.gradle
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/oauth/properties/AppleClientSecret.java
- src/main/java/tipitapi/drawmytoday/oauth/properties/ApplePrivateKey.java
- src/main/java/tipitapi/drawmytoday/oauth/properties/AppleProperties.java
- src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
- src/main/resources/application-oauth.yml
- src/test/java/tipitapi/drawmytoday/oauth/integrate/ApplePropertiesTest.java
기존 애플리케이션은 apple client secret을 환경변수에 저장하여 사용했습니다. 다만, apple client secret은 만료기간이 30일 이내의 jwt 토큰으로 만들어야 유효합니다. 따라서 29일이 지나면 수동으로 환경변수를 바꾸고, 애플리케이션을 다시 시작해야되는 불편함이 있습니다.
따라서 client secret을 환경변수가 아닌 애플리케이션 내부에서 생성하고, 관리하는 방식으로 변경하여 매 요청시 토큰 만료 여부를 확인하도록 구현했습니다. 만약 토큰이 만료되지 않았다면 기존 토큰을 활용하고, 만료됐다면 토큰을 새로 만들어 저장하고, 반환하는 형식입니다. 
구현 이후 [validate refresh token](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens#3605122) api를 호출하여 검증도 완료했습니다.
- BouncyCastle 라이브러리 의존성 추가
- 환경변수 APPLE_IOS_CLIENT_SECRET 삭제, APPLE_IOS_KEY_ID, APPLE_IOS_PRIVATE_KEY, APPLE_IOS_TEAM_ID 추가
- AppleClientSecret 클래스 구현
- AppleProperties 통합테스트 작성
---
__해당 PR이 머지되면 테스트 서버에 환경변수 등록 후 실제 애플 소셜로그인이 정상적으로 되는지 검증하겠습니다!__
close #13
> Apple client secret 생성 로직 추가

- src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
- 일기 생성 시 키워드가 없으면 eomtional이 아닌 emotions로 대체되도록 변경
close #140
> 일기 생성 시 키워드가 없으면 eomtional이 아닌 emotions로 대체되도록 변경

- .gitignore
- build.gradle
- src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
- src/main/java/tipitapi/drawmytoday/common/log/MDCRequestLoggingFilter.java
- src/main/resources/logback-spring.xml
로그 설정에 대해 정리가 필요할 것 같아 [노션 페이지](https://knowing-jester-927.notion.site/b8d2cedff35c46df9c3e08570982194c?pvs=4)에 Logback과 MDC를 정리했습니다!
- spring-boot-starter-logging 의존성 추가
- 각 월에 따라 로그 파일 분리
- 로그 파일 크기 100mb로 제한
- log에 request_id 추가(UUID)
close #138 
logback-spring.xml 파일을 작성하는 도중 코드를 저장하면 google code style에 따라 appender가 property보다 먼저 위치하도록 변경되어 appender가 property를 읽지 못하는 오류가 발생했습니다. 
따라서 xml 파일은 google code style의 위치 구성이 적용되지 않도록 
Editor -> Code Style -> XML 설정에서 Arrangement의 모든 코드 순서를 지웠습니다.(원래 property 순서만 조정하려 했는데 생각보다 property의 순서만 제외하기 쉽지 않아서 전부 지우는 다소 극단적인? 선택을 했습니다)
따라서 xml 파일에 대한 코드 순서가 통일되지 않지만.. 뷰 템플릿이나 MyBatis를 사용하지도 않기에 앞으로 xml 파일을 만들 경우가 없지 않을까 하는 생각이 듭니다. 하지만 다른 분들의 개발환경도 같은 환경을 구성해야 하기에 `Preference -> Editor -> Code Style -> XML 설정에서 Arrangement의 모든 순서` 를 지우셔야 할 것 같습니다.
> 로그 레벨에 따른 파일 분리 및 로그 설정 추가 

- src/main/java/tipitapi/drawmytoday/common/validator/DiaryDateValidator.java
- src/main/java/tipitapi/drawmytoday/common/validator/ValidDiaryDate.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
- src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/diary/service/ImageService.java
- src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
- src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
- src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/ImageServiceTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
=> `[POST] /diary` 일기 생성 API와 관련된 `diaryDate` 필드 검증 방식 변경, 코드 아키텍처 리팩토링
- `diaryDate`가 미래의 날짜인기 검증하는 Custom 어노테이션 `ValidDiaryDate` 와 그 Validator 클래스인 `DiaryDateValidator` 추가
- 기존의 `createDiary`에서 `diaryDate`를 검증하던 `validateCreateDiaryDate` 메소드 삭제
- CreateDiaryService와 기타 테스트 코드 등 여러 코드에서 일기 객체를 생성하는 로직이 필요함
- 기존에는 `빌더 패턴`으로 일기 객체를 생성했는데, 이는 각 파라미터를 매우 자율적으로 조정가능하므로, 일기의 객체의 유형이 변경되거나 파라미터가 변경되었을때 빌더 패턴을 사용한 모든 것의 변경이 수반됨
- 이를 개선하고자 일기 객체를 생성하는 메소드를 추가하였음
- 현재 비즈니스 로직상, 테스트용 일기와 일반 일기를 생성하는 두 경우로 나뉘므로 두개의 객체 생성 메소드 `of`, `ofTest`를 Diary 도메인 클래스에 추가함
- 이를 통해, 
- 일기를 생성할때 각 유형으로 획일화 되어 어디서든 생성할 수 있고
- 일기를 생성할때 isAi 필드와 같이 자율적으로 조정하는 행위를 도메인의 책임으로 이동시켰고
- 일기 생성시에 세부적인 로직이 변경되어도 도메인 코드만 수정할 수 있는 
이점을 취할 수 있음
- 기존에는 일기 생성 API 요청시 `CreateDiaryService.createDiary` 메소드에서 모든 요청을 받아 test ( boolean ) …
> 일기 생성 API와 관련된 diaryDate 필드 검증 방식 변경, 코드 아키텍처 리팩토링

- src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
- src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
일기 프롬프트 생성시 keyword가 100자를 넘을 경우 자르도록 처리
- 기존에는 keyword 필드를 DTO validation을 통해 최대 100자로 검증하였음
- 하지만, 앱에서 에러로 핸들링하기보다 서버 측에서 100자로 자르는 것이 비즈니스 로직상 적합한 것으로 논의됨에 따라, DTO Validation을 없애고 프롬프트 값을 생성할때 keyword의 길이를 100자 이하로 자르도록 처리함
close #135
> 일기 프롬프트 생성시 keyword가 100자를 넘을 경우 자르도록 처리

- src/main/java/tipitapi/drawmytoday/common/config/WebConfig.java
- src/main/java/tipitapi/drawmytoday/common/converter/Language.java
- src/main/java/tipitapi/drawmytoday/common/converter/StringToLanguageConverter.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/emotion/domain/Emotion.java
- src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
- GET "/diary/{id}" api에 lan 쿼리 파라미터 추가
- 쿼리 파라미터를 받을 Language enum 추가
- String 타입 lan을 Language enum으로 변환할 Converter 추가
- lan 값이 ko면 response dto의 emotion 필드에 emotion 엔티티의 name을, en이면 emotionPrompt를 반환
- getDiary 메서드 시그니처 변경으로 인해 달라진 테스트 코드 수정
lan 쿼리 파라미터를 String 값으로 받아도 되지만 Language enum을 도입한 이유는 앞으로 다국어 지원이 도입됨에 따라 쿼리 파라미터에 lan을 받는 api들이 많아질 것 같기에 lan 쿼리 파라미터에 대한 검증과 값을 추상화하기 위해서 입니다.
만약 해당 구현이 괜찮으시다면 모든 감정을 반환하는 api도 lan 쿼리 파라미터를 Language로 받도록 수정하겠습니다!
close #146
> 일기 조회 api에 lan 쿼리 파라미터 추가

- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
- src/main/java/tipitapi/drawmytoday/diary/exception/DiaryDateAlreadyExistsException.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepository.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/diary/service/ValidateDiaryService.java
- src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/ValidateDiaryServiceTest.java
[POST] /diary 일기 생성 API - 주어진 날짜로 생성된 일기가 있는지 검증
- DiaryDateAlreadyExistsException 예외 추가
- 주어진 날짜로 생성된 일기가 있다면 DiaryDateAlreadyExistsException 예외를 던짐
- queryDSL 기반의 getDiaryExistsByDiaryDate 레포지토리 메서드 추가. userId와 주어진 일자에 해당하는 일기 데이터를 반환함
[GET] /diary/calendar/date 특정 날짜 일기 존재 여부 조회 API - getDiaryExistsByDiaryDate 레포지토리 메서드를 사용하도록 변경
- 기존의 findByUserIdAndDiaryDate 레포지토리 메서드가 아닌 getDiaryExistsByDiaryDate 메서드를 사용하도록 변경
- findByUserIdAndDiaryDate 메서드 삭제, 관련 테스트 삭제
close #177
> 일기 생성시, 주어진 날짜로 생성된 일기가 있는지 검증

- src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
- src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
- src/main/java/tipitapi/drawmytoday/ticket/domain/Ticket.java
- src/main/java/tipitapi/drawmytoday/ticket/domain/TicketType.java
- src/main/java/tipitapi/drawmytoday/ticket/repository/TicketRepository.java
- src/main/java/tipitapi/drawmytoday/ticket/service/TicketService.java
- src/test/java/tipitapi/drawmytoday/ticket/service/TicketServiceTest.java
Ticket 엔티티 추가
- ticketType 필드를 통해 가입시 부여된 티켓인지, 광고를 통해 부여된 티켓인지 구분할 수 있도록 구성하였습니다.
- 사용일자를 기록하기 위해, usedAt 필드를 추가하였습니다.
TicketType Enum 추가
- JOIN, AD_REWARD 값을 가지고 있습니다.
- JOIN 값은 회원가입시 부여된 티켓의 종류를 나타냅니다.
- AD_REWARD 값은 광고를 시청함으로써 등록된 티켓의 종류를 나타냅니다.
[POST] /oauth2/google/login, [POST] /oauth2/apple/login : 구글 로그인 / 애플 로그인 시 티켓 7개 등록
- TicketService의 createTicketByJoin 메서드를 통해 로그인시 티켓 7개를 등록하도록 만들었습니다.
아래 sql을 추가해야합니다.
```sql
CREATE TABLE ticket (
ticket_id bigint NOT NULL AUTO_INCREMENT,
created_at datetime NOT NULL,
ticket_type varchar(255) NOT NULL,
used_at datetime,
user_id bigint NOT NULL,
PRIMARY KEY (ticket_id)
);
ALTER TABLE ticket
ADD FOREIGN KEY (user_id) REFERENCES user(user_id);
```
close #180
> Ticket 엔티티 추가, 회원 가입시 티켓 7개 부여

- src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
- src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/ticket/service/TicketService.java
- src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
- src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
- CreateDiaryRequest DTO에 userTime(요청하는 유저 로컬 시각) 추가
- GlobalExceptionHandler에서 HttpMessageNotReadableException을 잡아 커스텀 메시지를 반환하도록 추가
- 바뀐 시그니처에 따라 테스트 코드 수정
close #184
> 일기 생성시 Diary 엔티티의 diaryDate에 유저 현재 시각 받아서 저장

- src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryLimitResponse.java
- src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/ticket/repository/TicketQueryRepository.java
- src/main/java/tipitapi/drawmytoday/ticket/repository/TicketQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/ticket/repository/TicketRepository.java
- src/main/java/tipitapi/drawmytoday/ticket/service/TicketService.java
- src/main/java/tipitapi/drawmytoday/ticket/service/ValidateTicketService.java
- src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
- src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
- src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
- src/test/java/tipitapi/drawmytoday/ticket/repository/TicketRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/ticket/service/ValidateTicketServiceTest.java
- src/test/resources/tipitapi/drawmytoday/ticket/repository/ValidTicket.sql
[GET] /diary/limit 일기 생성 가능 여부 조회 API : 광고가 아닌, 티켓 기반으로 일기 생성 제한을 검증하도록 수정
- 기존에는 오늘 작성할 수 있는 일기를 이미 작성했을 때, 유효한 광고 리워드가 있는지 검증했습니다.
- 이때, 유효한 광고 리워드가 아닌 유효한 티켓을 통해 검증하도록 수정하였습니다.
- 리워드라는 명칭을 지양하도록, 응답 필드명을 수정했습니다. : rewardCreatedAt -> ticketCreatedAt
- 티켓을 가지고 있는지 검증하는 메서드를, 단순히 있는지를 검사하기 보다 유효한지를 검증해야한다고 생각합니다. 현재는 티켓 만료에 대한 ( 유효기간에 대한 ) 기준이 정해지지 않았지만, 추후 확장될 것을 고려해서 Valid 네이밍을 사용하도록 했습니다.
- 추후에는, TicketType(JOIN, AD_REWARD)에 따라 유효기간이 다르게 설정될것 같아 현재 적용하지 않은 점도 있습니다!
- 유저가 오늘 일기를 작성했는지 검증하지 않고, 유저가 티켓을 가지고 있는지 검증하도록 변경
- 따라서, user의 lastDiaryDate에 대한 검증 로직을 삭제하였습니다.
관리자 일기 조회시 사용되는 메서드의 테스트 코드 수정
- 관리자 일기 조회 API 수행시 사용되는 메서드에 대한 테스트 코드가 잘못 작성되어 있어 수정하였습니다.
close #185
> 티켓 기반의 일기 생성 제한 검증 기능 그리고 관리자 일기 조회 테스트 수정

- build.gradle
- JACOCO 커버리지에 Q파일 추적되는 이슈 해결
gradle로 테스트를 돌리면 jacoco 리포트가 작성됩니다.(jacocoTestReport task에 test를 dependsOn했기 때문입니다) 다만, 테스트가 하나라도 실패한다면 리포트는 작성되지 않습니다. 따라서 실패하는 테스트가 있다면 잠시 주석처리를 한다면 리포트를 확인할 수 있습니다.
리포트는 build/reports/jacoco/test/html/index.html에서 확인하실 수 있습니다.
close #204
> JACOCO 커버리지 Q파일 제거

- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/common/utils/HeaderUtils.java
- src/main/java/tipitapi/drawmytoday/domain/oauth/controller/AuthController.java
- src/main/java/tipitapi/drawmytoday/domain/oauth/domain/Auth.java
- src/main/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthService.java
- src/main/java/tipitapi/drawmytoday/domain/oauth/service/GoogleOAuthService.java
- src/main/java/tipitapi/drawmytoday/domain/user/domain/User.java
- src/main/java/tipitapi/drawmytoday/domain/user/service/UserService.java
- auth 도메인 서비스단 리팩토링
- 로그인시 authorization 헤더에서 값을 가져오는 로직, 회원가입하는 로직 분리
- Checked Exception -> UnChecked Exception으로 변환
- User 엔티티 email 필드 NotNull 추가
테스트 서버에 추가했으며 실서버 배포시 추가되어야 합니다.
```SQL
ALTER TABLE user MODIFY email VARCHAR(255) NOT NULL;
```
close #132 
close #214 
expected)
> OAuthService 리팩토링 및 User 엔티티 email 필드 not nullable

- src/main/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionController.java
- src/main/java/tipitapi/drawmytoday/domain/emotion/dto/GetActiveEmotionsResponse.java
- src/main/java/tipitapi/drawmytoday/domain/emotion/service/EmotionService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/EmotionServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionControllerTest.java
감정 목록 조회 API Language enum 적용
- String으로 lan 파라미터 값을 처리하는 로직 제거
close #221 
expected)
> 감정 목록 조회 API Language enum 적용

- src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallEPolicyViolationException.java
- src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallERequestService.java
- src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallEService.java
- src/test/java/tipitapi/drawmytoday/domain/dalle/service/DallERequestServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/dalle/service/DallEServiceTest.java
**dalle 도메인 서비스단 테스트코드 작성 중 mocking한 클래스의 같은 메서드 동작을 여러 번 정의할 때 파라미터의 값이 다를 때마다 다르게 동작하도록 구현하는 과정에서 복잡도가 많이 증가하는 이슈가 있었습니다. 따라서 dalle rest 요청을 실제로 호출하는 메서드를 다른 클래스로 분리했습니다.**
- dalle rest 요청 분리(DallERequestService 추가)
- dalle 도메인 서비스단 테스트코드 추가
close #226 
expected)
> Dalle 요청 로직 분리 및 서비스단 테스트 추가

- src/main/java/tipitapi/drawmytoday/domain/ticket/service/TicketService.java
- src/test/java/tipitapi/drawmytoday/domain/ticket/service/TicketServiceTest.java
정책 변경에 따라 회원가입시 티켓 1장만 발급되도록 변경해서 main에 바로 업데이트했습니다.
따라서 dev 브랜치에도 추가합니다!
Release 1.1.4 노트에도 추가하겠습니다!
expected)
> 회원가입시 티켓 1장만 발급되도록 변경

- src/main/java/tipitapi/drawmytoday/common/resolver/AuthUser.java
- src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/Diary.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/ReviewType.java
- src/main/java/tipitapi/drawmytoday/domain/diary/dto/ReviewDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
[POST] /diary/{id}/review
- diaryId에 해당하는 일기 그림 평가 API 생성
- ReviewType BAD, GOOD로 제한
close #230 
expected)
> 유저 그림 평가 기능 추가

- src/main/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/r2/service/R2PreSignedService.java
SK 브로드밴드 DNS 서버 문제로 R2 도메인이 아닌 커스텀 도메인으로 이미지 url을 생성하도록 변경했습니다.
커스텀 도메인은 pre-signed url을 발급하지 못하는 것으로 알고 있기에 만료시간 없이 url 자체를 발급하도록 변경했습니다.
이미지 폴더 경로로 이미지 url을 발급하는 책임은 R2 클래스가 맡는게 좋을거 같아 R2PreSignedService에 customDomainUrl을 발급하도록 구현했습니다. 다만, 이름을 R2PreSignedService에서 R2ImageUrlService로 변경하는것도 좋을거 같습니다!
- 이미지 조회 API, 월별 이미지 조회 API, admin 전체 이미지 조회 API시 발급됐던 pre-signed url을 custom domain url로 변경
expected)
> r2 이미지 조회시 커스텀 url로 조회하도록 변경

- src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
_정책 위반으로 프롬프트를 변경할 때_ 혹은 _아무런 키워드가 전달되지 않았을 때_, 
Oil Pastel 부분 프롬프트 뒤에 붙이던 'emotions' 프롬프트 키워드 값을 'portrait' 으로 변경하였습니다.
close #247 
expected)
> 이미지 개선을 위한 프롬프트 변경(emotions -> portrait) 

- src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/Image.java
- src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetImageResponse.java
- src/main/java/tipitapi/drawmytoday/domain/diary/exception/DiaryNeedsImageException.java
- src/main/java/tipitapi/drawmytoday/domain/diary/exception/SelectedImageDeletionDeniedException.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/ImageControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
- 대표 이미지 삭제 요청시 예외 발생 : SelectedImageDeletionDeniedException
- 요청한 이미지의 일기가 1개 이하의 이미지를 갖고 있는 경우 예외 발생 : DiaryNeedsImageException
- SoftDelete로 이미지 삭제 처리
- deleted_at 컬럼 추가 필요
- queryDSL 기반 Image Repository 생성
- 삭제된 이미지는 이미지 목록에서 제외하는 Repository 메서드 사용
- 기존에 일기 조회시 이미지 목록을 조회하기 위해 사용한 `findAllByDiaryDiaryIdOrderByCreatedAtDesc` Repository 메서드 삭제
- GetImageResponse 클래스에 이미지 ID 필드 추가
- 이미지 ID로 삭제 요청을 보낼 수 있어야하므로 이미지 ID 필드가 필요함
```sql
ALTER TABLE image ADD deleted_at datetime AFTER created_at;
```
deleted_at이 추가됨에 따라, 다른 ImageRepository 메소드도 `deletedAt is null` 쿼리문 추가가 필요합니다.
다만, 같은 PR에서 구현할 경우 PR이 커질 수 있으므로 별도로 작업할 예정입니다 ( 관련 이슈 : #250 )
close #249 
expected)
> 이미지 삭제 API 추가 및 일기 조회 API 수정

- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
- findAllByDiaryDiaryId 메서드는 deletedAt = null 이 반영되어 있지 않아서, queryDSL 기반 메서드 findByDiary를 추가하여 교체함
- ImageQueryRepository, ImageQueryRepositoryImpl에 새로운 메서드를 추가함
- findAllByDiaryDiaryId메서드를 사용하는 unSelectAllImage에 대해 findByDiary를 사용하도록 교체함
- ImageRepositoryTest 반영
- ImageService의 getImage, getImages 메서드가 사용되지 않아 삭제함
- 이에 따라, getImage가 사용하고 있던 이미지 레포지토리 메서드인 findByIsSelectedTrueAndDiary도 삭제함
close #250 
expected)
> ImageRepository QueryDSL 적용에 따른 이관

- src/main/java/tipitapi/drawmytoday/domain/diary/domain/Diary.java
- src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetMonthlyDiariesResponse.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
Before: 월별 일기 반환 API에서 각 일기별로 반환되는 imageUrl은 가장 옛날에 그린 이미지의 imageUrl 한 개
After: 월별 일기 반환 API에서 각 일기별로 반환되는 imageUrl은 일기의 대표 이미지의 imageUrl 한 개
- diaryId에 해당하는 대표 이미지가 없다면?
1. 에러 로그를 남긴다.
2. 리스트에서 해당 일기를 제외하여 반환한다.
- 만약 diaryId에 해당하는 대표 이미지가 여러 개라면?
가장 최근에 생성한 이미지를 반환한다.
- queryDSL + DTO projection으로 월별 일기 목록 조회하도록 변경
- 실패하는 테스트 수정
close #252
expected)
> [월별 일기 반환 API] 대표 이미지가 반환되지 않는 문제 해결

- src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ValidateImageService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/controller/ImageControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
- 컨트롤러, 컨트롤러 테스트, 서비스, 서비스 테스트 추가
- ValidateImageService.validateImageById 메서드는 imageRepository.findById를 호출했었으나, 이는 삭제된 이미지를 제외하지 않습니다.
- 따라서 imageRepository.findImage 메서드로 교체하였습니다.
close #255 
expected)
> 대표 이미지 설정 API 추가

- src/main/java/tipitapi/drawmytoday/domain/admin/dto/GetDiaryAdminResponse.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
- src/test/java/tipitapi/drawmytoday/domain/admin/controller/AdminControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/admin/service/AdminServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
- GetAdminDiaryResponse 에 이미지 평가 review, 이미지 생성 시간 imageCreatedAt 필드 추가
- 이미지를 기준으로 리턴해야했는데, 이미지 Left Outer Join이 적용되어 있어 하나의 일기당 여러개의 이미지 컬럼을 작업할 수 있는 구조임
- 또한, 이미지를 기준으로 리턴해야하지만, 감정 필터링이나 프롬프트 매칭 때문에 Diary를 기준으로 이미지를 조회해야만 함
close #254 
expected)
> [관리자 일기 목록 API] 이미지 평가, 이미지 생성 시간 필드 추가

- src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetMonthlyDiariesResponse.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
**월별 일기 목록 조회시 대표 이미지가 없을 경우 로직 구현**
1. 월별 일기 목록 조회 API 호출 
(이후 검증 및 한 달 간의 일기 조회 로직 동작)
2. 한 달 간의 일기들을 순회하면서 대표 이미지 조회
3. (순회 중) 대표 이미지가 없을 경우 가장 최신 이미지 조회
4-1. (이미지가 있을 경우) 해당 이미지를 대표 이미지로 설정
4-2. (이미지가 없을 경우) 해당 일기는 월별 일기 목록에서 제외 (종료)
5. 대표 이미지로 설정한 이미지 반환
6. 한 달 간의 일기들 반환
- 실패하는 테스트 수정 및 구현한 로직 테스트코드 추가
close #258 
expected)
> [월별 일기 목록 API] 대표 이미지가 없을 경우 분기 처리 추가

- src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
- src/main/java/tipitapi/drawmytoday/domain/diary/controller/TestDiaryController.java
- src/main/java/tipitapi/drawmytoday/domain/diary/dto/CreateTestDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/service/DallEService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/KarloUrlResponse.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/service/ImageGeneratorService.java
- [ POST `/diary` ]: test 쿼리 파라미터 삭제(기존의 테스트 일기 생성 로직 삭제)
- [ POST `/diary/test` ]: 테스트 일기 생성 API 구현
- TestDiaryController 생성(prod 프로필이 아닐 경우 활성화)
- 테스트 일기 생성 시 파라미터 추가(prompt, negativePrompt, samples, priorNumInferenceSteps, priorGuidanceScale, seed)
테스트 일기 생성 API가 머지되면 실패하는 테스트 및 테스트 일기 생성 API 테스트 코드 작성하겠습니다. #266 
[일기 생성 API에서 쿼리 파라미터로 테스트 일기 작성하는 로직이 사라졌으니 해당 이슈도 닫겠습니다]
close #137 
close #264 
expected)
> 테스트 일기 생성 API 구현

- src/main/java/tipitapi/drawmytoday/domain/admin/controller/AdminController.java
- src/main/java/tipitapi/drawmytoday/domain/admin/dto/GetDiaryAdminResponse.java
- src/main/java/tipitapi/drawmytoday/domain/admin/service/AdminService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryService.java
- src/test/java/tipitapi/drawmytoday/domain/admin/controller/AdminControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/admin/service/AdminServiceTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/repository/DiaryRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
- 쿼리 파라미터 `test` 를 추가해서, 해당 파라미터 값에 따라 테스트 일기 반환 여부를 판단
- 쿼리 파라미터 `test`는 기본적으로 true로, 기본적으로 테스트 일기를 포함하도록 구현
- controller, service, repository 메서드에 파라미터를 추가하고, 파라미터 값에 따라서 where 절 쿼리를 추가하도록 로직 추가
- `GetAdminDiaryResponse` Response DTO 객체에 해당 일기 객체가 테스트 일기인지 여부를 알 수 있도록, `isTest` 필드 추가
close #269 
expected)
> [관리자 일기 조회 API] 테스트 일기가 반환되도록 개선

- src/main/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionController.java
- src/main/java/tipitapi/drawmytoday/domain/emotion/dto/GetActiveEmotionsResponse.java
- src/main/java/tipitapi/drawmytoday/domain/emotion/service/EmotionService.java
- src/test/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionControllerTest.java
- src/test/java/tipitapi/drawmytoday/domain/emotion/repository/EmotionRepositoryTest.java
- src/test/java/tipitapi/drawmytoday/domain/emotion/service/EmotionServiceTest.java
- 기존에는 영어 / 한국어로 응답을 제공했으나, 이를 영어로 통일함
- 쿼리 파라미터 적용 로직 삭제
- 메서드 파라미터 및 로직, 테스트 삭제
- emotionService, emotionRepository 에 대한 테스트코드가 diary 패키지 내에 위치해있어, emotion 패키지로 이동함
close #278 
expected)
> 감정 목록 조회시 영어로 응답 통일

- .github/workflows/cd.yml
- src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
- src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestService.java
- src/main/resources/application-kakao.yml
- src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestServiceTest.java
노션에 추가된 환경변수 작성했습니다. 
또한, Github Actions secret에도 추가했습니다.
- 화풍 프롬프트, negative 프롬프트를  환경변수에서 받아오도록 변경
- nude, digital 네거티브 프롬프트 추가
- 실패하는 테스트 추가
- 테스트 서버에 환경변수 추가
close #276 
expected)
> 프롬프트 환경변수화 및 네거티브 프롬프트 추가

- build.gradle
- src/main/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthService.java
- jackson-databind와 jackson-annotations의 버전 불일치로 인한 에러 해결
- 자세한 내용 [참조](https://twofootdog.tistory.com/105)
- 애플 소셜탈퇴시 ErrorResponse가 반환될 때만 실패하도록 변경
expected)
> jackson-databind와 다른 의존성간 버전 충돌 문제 및 애플 소셜탈퇴 문제 해결

- src/main/java/tipitapi/drawmytoday/common/exception/BusinessException.java
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthService.java
애플 소셜로그인 회원탈퇴 시도 -> 200 응답 성공(다만, 애플 계정에서 애플로 로그인된 앱을 확인하면 정상적으로 탈퇴되지 않은 것을 볼 수 있음) -> 애플로그인 재시도 -> 프론트로부터 받은 idToken을 파싱해도 이메일을 얻을 수 없음(왜..?) -> 이메일이 없기에 회원가입 실패
Q. refresh token으로 해당 토큰이 만료됐는지 확인할 수 있음. 만약 회원탈퇴가 정상적으로 처리되지 않았다면 토큰이 만료되지 않았다고 뜨지 않을까?
A. 회원 탈퇴 시도 시 200 응답은 떳지만 회원탈퇴가 안된 상황에서도 refresh token은 만료됨(애플 소셜서버를 어떻게 만든거야..)
백단은 애플 소셜로그인 시 이메일이 없다면 이메일이 없다는 에러를 반환하도록 하고, 프론트단에서 유저에게 직접 계정에 들어가 회원탈퇴하도록 유도하는 방향이 최선일거 같습니다.
- businessException에 message를 추가하도록 변경(에러 로그시 null값이 뜨기 때문)
- 애플 소셜로그인시 이메일을 못 받으면 에러를 던지도록 수정
close #291 
expected)
> 애플 소셜로그인 회원탈퇴 실패 이슈

- src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
- 급하게 운영 서버에 배포하느라 무중단 배포 작업본과 함께 main 브랜치에 머지했습니다. 해당 PR 머지되면 배포 PR 만들겠습니다!(실제 배포 actions는 취소하겠습니다)
close # (issue)
expected)
> 특정 날짜 일기 존재 여부 조회시 2월 29일을 정상적인 값으로 받지 않는 이슈 해결

- .github/workflows/cd.yml
- src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/PromptGeneratorResult.java
- src/main/java/tipitapi/drawmytoday/domain/diary/exception/PromptNotFoundException.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/PromptRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/ValidatePromptService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/dto/GptChatCompletionsRequest.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/service/GptService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/service/TextGeneratorService.java
- src/main/resources/application-openai.yml
- 일기 재생성시 기존 gpt 히스토리가 없다면 gpt 히스토리 없이 gpt 호출하도록 구현
- 일기 재생성시 기존 gpt 히스토리가 있다면 `gpt history + gpt regenerate prompt(형원's prompt) + 번역된 일기`로 호출하도록 구현
close #306
expected)
> 일기 재생성시 기존 GPT 요청 정보를 포함하도록 변경

- src/main/java/tipitapi/drawmytoday/common/config/TransactionTemplateConfig.java
- src/main/java/tipitapi/drawmytoday/domain/admin/controller/AdminController.java
- src/main/java/tipitapi/drawmytoday/domain/admin/dto/GetDiaryNoteAndPromptResponse.java
- src/main/java/tipitapi/drawmytoday/domain/admin/service/AdminService.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/Prompt.java
- src/main/java/tipitapi/drawmytoday/domain/diary/domain/PromptGeneratorResult.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepository.java
- src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/google/service/GoogleTranslatorService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/service/TranslateTextService.java
- GPT Generator Content 추가 API[admin/add-gpt-generator-content] 생성
- api 호출당 reputation(query param) x 10개의 gpt generator content가 생성되도록 구현
- 한 reputation은 10개의 병렬 쓰레드로 google translator를 호출하고 결과를 db에 저장하며, 모든 쓰레드가 task를 수행하면  다음 reputation으로 넘어가도록 구현
- 한 reputation 내 10개의 병렬 쓰레드가 모두 gpt generator content 만드는데 실패했다면, 종료
- 명시적 transaction 주입을 위한 TransactionTemplate 생성
close #307 
expected)
> 일기 프롬프트 생성을 위해 호출한 GPT History를 모든 일기가 갖도록 변경

- src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/domain/Message.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/service/GptService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/service/TextGeneratorService.java
- 프롬프트 생성을 위한 gpt api response로 프롬프트를 만들 때, 150글자 이하로 clamping
- gpt response는 clamping하지 않고 그대로 저장
close #314
expected)
> 프롬프트 생성을 위해 호출하는 gpt response의 content 길이 150자 이하로 clamping한다

- src/main/java/tipitapi/drawmytoday/domain/diary/dto/ReviewDiaryRequest.java
- src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/domain/Message.java
- src/main/java/tipitapi/drawmytoday/domain/generator/api/gpt/service/GptService.java
- src/main/java/tipitapi/drawmytoday/domain/generator/service/TextGeneratorService.java
- 프롬프트 생성을 위한 gpt api response로 프롬프트를 만들 때, 150글자 이하로 clamping
- gpt response는 clamping하지 않고 그대로 저장
- review 값이 숫자가 아니거나 없으면 예외 반환
- 숫자 값이 1보다 작으면 1로 변환
- 숫자 값이 5보다 크면 5로 변환
close #314
close #315
expected)
> Release 1.3.1
